# This is the network config written by 'subiquity'
network:
  renderer: networkd
  ethernets:
    ens160:
      dhcp4: no
      addresses: [10.0.5.201/24]
      gateway4: 10.0.5.2
      nameservers:
        addresses: [10.0.5.2]
  version: 2
